[project]
name = "llm-engineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "dotenv>=0.9.9",
    "groq>=0.30.0",
    "ollama>=0.5.1",
    "openai>=1.98.0",
    "requests>=2.32.4",
]
